export {About} from "./About.jsx"
export {Home} from "./Home"
export {Navbar} from "./Navbar"
export {Contact} from "./Contact"
export {UserProfile} from "./UserProfile"
export {Admin} from "./Admin"
export {Settings} from "./Settings"
export {Dashboard} from "./Dashboard"